# Konfigurasjon for BilvaskRegistrering
CameraRtspUrl=rtsp://admin:K93v2nvp20@192.168.178.200:554/cam/realmonitor?channel=1&subtype
PlateRecognizerApiToken=2ad8c2e4-85ed-0001-4b85-0ebc417b85ed
DahuaHost=192.168.178.200
DahuaPort=37777
DahuaUsername=admin
DahuaPassword=K93v2nvp20
ItsApiPort=7070
ItsApiPath=/NotificationInfo/TollgateInfo
ItsApiHostIp=192.168.178.50
DocFolder=C:\Users\bogus\OneDrive\Dokumenty\BilvaskRegistrering
AutoRegisterOnPlate=True
DisplaySeconds=20
