// <auto-generated>
// This file was created to move the UI layout of WorkerForm into the WinForms Designer.
// Edit the layout visually in Visual Studio (Designer). Keep runtime logic in WorkerForm.cs.
// </auto-generated>

using System;
using System.ComponentModel;
using System.Drawing;
using System.Windows.Forms;

namespace BilvaskRegistrering.Worker;

partial class WorkerForm
{
    private IContainer? components = null;

    // Root containers
    private TableLayoutPanel _root = null!;
    private GroupBox _leftOuter = null!;
    private TableLayoutPanel _left = null!;
    private Label _lblPlateCaption = null!;
    private Panel _plateHost = null!;
    private Label _spacer1 = null!;
    private Label _spacer2 = null!;
    private TableLayoutPanel _leftBottom = null!;
    private GroupBox _gbType = null!;
    private TableLayoutPanel _typeLayout = null!;
    private GroupBox _gbComment = null!;
    private TableLayoutPanel _right = null!;
    private GroupBox _listOuter = null!;
    private TableLayoutPanel _listLayout = null!;
    private TableLayoutPanel _filterBar = null!;
    private TableLayoutPanel _header = null!;
    private Label _lblPeriodeLabel = null!;
    private Label _lblFraLabel = null!;
    private Label _lblTilLabel = null!;
    private Label _lblAnsLabel = null!;

    // Controls used by runtime logic (WorkerForm.cs)
    private ComboBox _cmbAnsatt = null!;
    private TextBox _txtKommentar = null!;
    private ComboBox _cmbPeriode = null!;
    private DateTimePicker _dtpFra = null!;
    private DateTimePicker _dtpTil = null!;
    private Button _btnSettings = null!;

    private RadioButton _rbInOut = null!;
    private RadioButton _rbOut = null!;
    private RadioButton _rbIn = null!;
    private RadioButton _rbHeldag = null!;
    private RadioButton _rbSjekket = null!;

    private RadioButton _rbInOutDiesel = null!;
    private RadioButton _rbDiesel = null!;
    private RadioButton _rbGjennom = null!;

    private Label _lblPlate = null!;
    private Label _lblInternnr = null!;
    private Label _lblTypeKjoretoy = null!;
    private Label _lblSesong = null!;
    private Label _lblStatusValue = null!;
    private Label _lblDato = null!;
    private CheckBox _chkOnlyUnconfirmed = null!;
    private DataGridView _grid = null!;
    private Label _lblDbStatus = null!;
    private Label _lblInternPickLabel = null!;
    private ComboBox _cmbInternPick = null!;
    private Button _btnLagreSjekket = null!;

    protected override void Dispose(bool disposing)
    {
        if (disposing)
        {
            try { components?.Dispose(); } catch { }
        }
        base.Dispose(disposing);
    }

    private void InitializeComponent()
    {
        _root = new TableLayoutPanel();
        _leftOuter = new GroupBox();
        _left = new TableLayoutPanel();
        _lblPlateCaption = new Label();
        _plateHost = new Panel();
        _lblPlate = new Label();
        _lblInternnr = new Label();
        _spacer1 = new Label();
        _lblDato = new Label();
        _lblTypeKjoretoy = new Label();
        _lblSesong = new Label();
        _lblStatusValue = new Label();
        _spacer2 = new Label();
        _leftBottom = new TableLayoutPanel();
        _gbType = new GroupBox();
        _typeLayout = new TableLayoutPanel();
        _rbInOut = new RadioButton();
        _rbInOutDiesel = new RadioButton();
        _rbOut = new RadioButton();
        _rbIn = new RadioButton();
        _rbHeldag = new RadioButton();
        _rbDiesel = new RadioButton();
        _rbSjekket = new RadioButton();
        _rbGjennom = new RadioButton();
        _gbComment = new GroupBox();
        _txtKommentar = new TextBox();
        _right = new TableLayoutPanel();
        _listOuter = new GroupBox();
        _listLayout = new TableLayoutPanel();
        _filterBar = new TableLayoutPanel();
        _btnRefresh = new Button();
        _btnConfirm = new Button();
        _lblPeriodeLabel = new Label();
        _cmbPeriode = new ComboBox();
        _lblFraLabel = new Label();
        _dtpFra = new DateTimePicker();
        _lblTilLabel = new Label();
        _dtpTil = new DateTimePicker();
        _pnlCamStatus = new Panel();
        _lblCamStatus = new Label();
        _btnSettings = new Button();
        _header = new TableLayoutPanel();
        _lblAnsLabel = new Label();
        _cmbAnsatt = new ComboBox();
        _chkOnlyUnconfirmed = new CheckBox();
        _lblInternPickLabel = new Label();
        _cmbInternPick = new ComboBox();
        _btnLagreSjekket = new Button();
        _lblDbStatus = new Label();
        _lblStatus = new Label();
        _grid = new DataGridView();
        _root.SuspendLayout();
        _leftOuter.SuspendLayout();
        _left.SuspendLayout();
        _plateHost.SuspendLayout();
        _leftBottom.SuspendLayout();
        _gbType.SuspendLayout();
        _typeLayout.SuspendLayout();
        _gbComment.SuspendLayout();
        _right.SuspendLayout();
        _listOuter.SuspendLayout();
        _listLayout.SuspendLayout();
        _filterBar.SuspendLayout();
        _pnlCamStatus.SuspendLayout();
        _header.SuspendLayout();
        ((ISupportInitialize)_grid).BeginInit();
        SuspendLayout();
        // 
        // _root
        // 
        _root.BackColor = Color.White;
        _root.ColumnCount = 2;
        _root.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 505F));
        _root.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        _root.Controls.Add(_leftOuter, 0, 0);
        _root.Controls.Add(_right, 1, 0);
        _root.Dock = DockStyle.Fill;
        _root.Location = new Point(0, 0);
        _root.Name = "_root";
        _root.Padding = new Padding(16);
        _root.RowCount = 3;
        _root.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        _root.RowStyles.Add(new RowStyle(SizeType.Absolute, 32F));
        _root.RowStyles.Add(new RowStyle(SizeType.Absolute, 8F));
        _root.Size = new Size(1845, 900);
        _root.TabIndex = 0;
        // 
        // _leftOuter
        // 
        _leftOuter.Controls.Add(_left);
        _leftOuter.Dock = DockStyle.Fill;
        _leftOuter.Location = new Point(19, 19);
        _leftOuter.Name = "_leftOuter";
        _leftOuter.Padding = new Padding(14);
        _leftOuter.Size = new Size(499, 822);
        _leftOuter.TabIndex = 0;
        _leftOuter.TabStop = false;
        _leftOuter.Text = "Valgt kjøretøy";
        // 
        // _left
        // 
        _left.BackColor = Color.White;
        _left.ColumnCount = 1;
        _left.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 20F));
        _left.Controls.Add(_lblPlateCaption, 0, 0);
        _left.Controls.Add(_plateHost, 0, 1);
        _left.Controls.Add(_lblInternnr, 0, 2);
        _left.Controls.Add(_spacer1, 0, 3);
        _left.Controls.Add(_lblDato, 0, 4);
        _left.Controls.Add(_lblTypeKjoretoy, 0, 5);
        _left.Controls.Add(_lblSesong, 0, 6);
        _left.Controls.Add(_lblStatusValue, 0, 7);
        _left.Controls.Add(_spacer2, 0, 8);
        _left.Controls.Add(_leftBottom, 0, 9);
        _left.Dock = DockStyle.Fill;
        _left.Location = new Point(14, 30);
        _left.Name = "_left";
        _left.RowCount = 10;
        _left.RowStyles.Add(new RowStyle(SizeType.Absolute, 28F));
        _left.RowStyles.Add(new RowStyle(SizeType.Absolute, 140F));
        _left.RowStyles.Add(new RowStyle(SizeType.Absolute, 86F));
        _left.RowStyles.Add(new RowStyle(SizeType.Absolute, 18F));
        _left.RowStyles.Add(new RowStyle(SizeType.Absolute, 34F));
        _left.RowStyles.Add(new RowStyle(SizeType.Absolute, 34F));
        _left.RowStyles.Add(new RowStyle(SizeType.Absolute, 34F));
        _left.RowStyles.Add(new RowStyle(SizeType.Absolute, 34F));
        _left.RowStyles.Add(new RowStyle(SizeType.Absolute, 18F));
        _left.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        _left.Size = new Size(471, 778);
        _left.TabIndex = 0;
        // 
        // _lblPlateCaption
        // 
        _lblPlateCaption.Dock = DockStyle.Fill;
        _lblPlateCaption.Font = new Font("Segoe UI", 12F, FontStyle.Bold);
        _lblPlateCaption.Location = new Point(3, 0);
        _lblPlateCaption.Name = "_lblPlateCaption";
        _lblPlateCaption.Size = new Size(465, 28);
        _lblPlateCaption.TabIndex = 0;
        _lblPlateCaption.Text = "Registreringsnummer";
        _lblPlateCaption.TextAlign = ContentAlignment.BottomLeft;
        // 
        // _plateHost
        // 
        _plateHost.BackColor = Color.White;
        _plateHost.Controls.Add(_lblPlate);
        _plateHost.Dock = DockStyle.Fill;
        _plateHost.Location = new Point(0, 28);
        _plateHost.Margin = new Padding(0);
        _plateHost.Name = "_plateHost";
        _plateHost.Size = new Size(471, 140);
        _plateHost.TabIndex = 1;
        // 
        // _lblPlate
        // 
        _lblPlate.BackColor = Color.White;
        _lblPlate.Dock = DockStyle.Fill;
        _lblPlate.Font = new Font("Segoe UI", 56F, FontStyle.Bold);
        _lblPlate.Location = new Point(0, 0);
        _lblPlate.Name = "_lblPlate";
        _lblPlate.Size = new Size(471, 140);
        _lblPlate.TabIndex = 0;
        _lblPlate.Text = "–";
        _lblPlate.TextAlign = ContentAlignment.MiddleCenter;
        // 
        // _lblInternnr
        // 
        _lblInternnr.Dock = DockStyle.Fill;
        _lblInternnr.Font = new Font("Segoe UI", 32F, FontStyle.Bold);
        _lblInternnr.Location = new Point(3, 168);
        _lblInternnr.Name = "_lblInternnr";
        _lblInternnr.Size = new Size(465, 86);
        _lblInternnr.TabIndex = 2;
        _lblInternnr.Text = "Internnr: –";
        _lblInternnr.TextAlign = ContentAlignment.MiddleLeft;
        // 
        // _spacer1
        // 
        _spacer1.Dock = DockStyle.Fill;
        _spacer1.Location = new Point(3, 254);
        _spacer1.Name = "_spacer1";
        _spacer1.Size = new Size(465, 18);
        _spacer1.TabIndex = 3;
        _spacer1.Text = " ";
        // 
        // _lblDato
        // 
        _lblDato.Dock = DockStyle.Fill;
        _lblDato.Font = new Font("Segoe UI", 16F);
        _lblDato.Location = new Point(3, 272);
        _lblDato.Name = "_lblDato";
        _lblDato.Size = new Size(465, 34);
        _lblDato.TabIndex = 4;
        _lblDato.Text = "Dato: –";
        _lblDato.TextAlign = ContentAlignment.MiddleLeft;
        // 
        // _lblTypeKjoretoy
        // 
        _lblTypeKjoretoy.Dock = DockStyle.Fill;
        _lblTypeKjoretoy.Font = new Font("Segoe UI", 16F);
        _lblTypeKjoretoy.Location = new Point(3, 306);
        _lblTypeKjoretoy.Name = "_lblTypeKjoretoy";
        _lblTypeKjoretoy.Size = new Size(465, 34);
        _lblTypeKjoretoy.TabIndex = 5;
        _lblTypeKjoretoy.Text = "Type kjøretøy: –";
        _lblTypeKjoretoy.TextAlign = ContentAlignment.MiddleLeft;
        // 
        // _lblSesong
        // 
        _lblSesong.Dock = DockStyle.Fill;
        _lblSesong.Font = new Font("Segoe UI", 16F);
        _lblSesong.Location = new Point(3, 340);
        _lblSesong.Name = "_lblSesong";
        _lblSesong.Size = new Size(465, 34);
        _lblSesong.TabIndex = 6;
        _lblSesong.Text = "Sesong: –";
        _lblSesong.TextAlign = ContentAlignment.MiddleLeft;
        // 
        // _lblStatusValue
        // 
        _lblStatusValue.Dock = DockStyle.Fill;
        _lblStatusValue.Font = new Font("Segoe UI", 16F);
        _lblStatusValue.Location = new Point(3, 374);
        _lblStatusValue.Name = "_lblStatusValue";
        _lblStatusValue.Size = new Size(465, 34);
        _lblStatusValue.TabIndex = 7;
        _lblStatusValue.Text = "Status: –";
        _lblStatusValue.TextAlign = ContentAlignment.MiddleLeft;
        // 
        // _spacer2
        // 
        _spacer2.Dock = DockStyle.Fill;
        _spacer2.Location = new Point(3, 408);
        _spacer2.Name = "_spacer2";
        _spacer2.Size = new Size(465, 18);
        _spacer2.TabIndex = 8;
        _spacer2.Text = " ";
        // 
        // _leftBottom
        // 
        _leftBottom.ColumnCount = 1;
        _leftBottom.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 20F));
        _leftBottom.Controls.Add(_gbType, 0, 0);
        _leftBottom.Controls.Add(_gbComment, 0, 1);
        _leftBottom.Dock = DockStyle.Fill;
        _leftBottom.Location = new Point(3, 429);
        _leftBottom.Name = "_leftBottom";
        _leftBottom.RowCount = 2;
        _leftBottom.RowStyles.Add(new RowStyle(SizeType.Absolute, 310F));
        _leftBottom.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        _leftBottom.Size = new Size(465, 346);
        _leftBottom.TabIndex = 9;
        // 
        // _gbType
        // 
        _gbType.AutoSize = true;
        _gbType.AutoSizeMode = AutoSizeMode.GrowAndShrink;
        _gbType.Controls.Add(_typeLayout);
        _gbType.Dock = DockStyle.Fill;
        _gbType.Location = new Point(3, 3);
        _gbType.Name = "_gbType";
        _gbType.Padding = new Padding(12);
        _gbType.Size = new Size(459, 304);
        _gbType.TabIndex = 0;
        _gbType.TabStop = false;
        _gbType.Text = "Type vask";
        // 
        // _typeLayout
        // 
        _typeLayout.ColumnCount = 1;
        _typeLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 15F));
        _typeLayout.Controls.Add(_rbInOut, 0, 0);
        _typeLayout.Controls.Add(_rbInOutDiesel, 0, 1);
        _typeLayout.Controls.Add(_rbOut, 0, 2);
        _typeLayout.Controls.Add(_rbIn, 0, 3);
        _typeLayout.Controls.Add(_rbHeldag, 0, 4);
        _typeLayout.Controls.Add(_rbDiesel, 0, 5);
        _typeLayout.Controls.Add(_rbSjekket, 0, 6);
        _typeLayout.Controls.Add(_rbGjennom, 0, 8);
        _typeLayout.Dock = DockStyle.Fill;
        _typeLayout.Location = new Point(12, 28);
        _typeLayout.Name = "_typeLayout";
        _typeLayout.RowCount = 9;
        _typeLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 30F));
        _typeLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 30F));
        _typeLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 30F));
        _typeLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 30F));
        _typeLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 30F));
        _typeLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 30F));
        _typeLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 30F));
        _typeLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 15F));
        _typeLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 30F));
        _typeLayout.Size = new Size(435, 264);
        _typeLayout.TabIndex = 0;
        // 
        // _rbInOut
        // 
        _rbInOut.Checked = true;
        _rbInOut.Dock = DockStyle.Fill;
        _rbInOut.Font = new Font("Segoe UI", 12F);
        _rbInOut.Location = new Point(3, 3);
        _rbInOut.Name = "_rbInOut";
        _rbInOut.Padding = new Padding(6, 0, 0, 0);
        _rbInOut.Size = new Size(429, 24);
        _rbInOut.TabIndex = 0;
        _rbInOut.TabStop = true;
        _rbInOut.Text = "Innvendig/utvendig vask";
        // 
        // _rbInOutDiesel
        // 
        _rbInOutDiesel.Dock = DockStyle.Fill;
        _rbInOutDiesel.Font = new Font("Segoe UI", 12F);
        _rbInOutDiesel.Location = new Point(3, 33);
        _rbInOutDiesel.Name = "_rbInOutDiesel";
        _rbInOutDiesel.Padding = new Padding(6, 0, 0, 0);
        _rbInOutDiesel.Size = new Size(429, 24);
        _rbInOutDiesel.TabIndex = 1;
        _rbInOutDiesel.Text = "Innvendig/utvendig vask/fylt diesel";
        // 
        // _rbOut
        // 
        _rbOut.Dock = DockStyle.Fill;
        _rbOut.Font = new Font("Segoe UI", 12F);
        _rbOut.Location = new Point(3, 63);
        _rbOut.Name = "_rbOut";
        _rbOut.Padding = new Padding(6, 0, 0, 0);
        _rbOut.Size = new Size(429, 24);
        _rbOut.TabIndex = 2;
        _rbOut.Text = "Kun utvendig vask";
        // 
        // _rbIn
        // 
        _rbIn.Dock = DockStyle.Fill;
        _rbIn.Font = new Font("Segoe UI", 12F);
        _rbIn.Location = new Point(3, 93);
        _rbIn.Name = "_rbIn";
        _rbIn.Padding = new Padding(6, 0, 0, 0);
        _rbIn.Size = new Size(429, 24);
        _rbIn.TabIndex = 3;
        _rbIn.Text = "Kun innvendig vask";
        // 
        // _rbHeldag
        // 
        _rbHeldag.Dock = DockStyle.Fill;
        _rbHeldag.Font = new Font("Segoe UI", 12F);
        _rbHeldag.Location = new Point(3, 123);
        _rbHeldag.Name = "_rbHeldag";
        _rbHeldag.Padding = new Padding(6, 0, 0, 0);
        _rbHeldag.Size = new Size(429, 24);
        _rbHeldag.TabIndex = 4;
        _rbHeldag.Text = "Heldag-nedvask";
        // 
        // _rbDiesel
        // 
        _rbDiesel.Dock = DockStyle.Fill;
        _rbDiesel.Font = new Font("Segoe UI", 12F);
        _rbDiesel.Location = new Point(3, 153);
        _rbDiesel.Name = "_rbDiesel";
        _rbDiesel.Padding = new Padding(6, 0, 0, 0);
        _rbDiesel.Size = new Size(429, 24);
        _rbDiesel.TabIndex = 5;
        _rbDiesel.Text = "Fylt diesel";
        // 
        // _rbSjekket
        // 
        _rbSjekket.Dock = DockStyle.Fill;
        _rbSjekket.Font = new Font("Segoe UI", 12F);
        _rbSjekket.Location = new Point(3, 183);
        _rbSjekket.Name = "_rbSjekket";
        _rbSjekket.Padding = new Padding(6, 0, 0, 0);
        _rbSjekket.Size = new Size(429, 24);
        _rbSjekket.TabIndex = 6;
        _rbSjekket.Text = "Kun sjekket";
        // 
        // _rbGjennom
        // 
        _rbGjennom.Dock = DockStyle.Fill;
        _rbGjennom.Font = new Font("Segoe UI", 12F);
        _rbGjennom.Location = new Point(3, 228);
        _rbGjennom.Name = "_rbGjennom";
        _rbGjennom.Padding = new Padding(6, 0, 0, 0);
        _rbGjennom.Size = new Size(429, 33);
        _rbGjennom.TabIndex = 10;
        _rbGjennom.Text = "Kun gjennom kjøring";
        // 
        // _gbComment
        // 
        _gbComment.Controls.Add(_txtKommentar);
        _gbComment.Dock = DockStyle.Fill;
        _gbComment.Font = new Font("Segoe UI", 9.75F, FontStyle.Bold, GraphicsUnit.Point, 238);
        _gbComment.ForeColor = Color.Red;
        _gbComment.Location = new Point(3, 313);
        _gbComment.Name = "_gbComment";
        _gbComment.Padding = new Padding(12);
        _gbComment.Size = new Size(459, 30);
        _gbComment.TabIndex = 1;
        _gbComment.TabStop = false;
        _gbComment.Text = "Uregistrert skade (Det er obligatorisk å inkludere bilde(r) i VognApp)";
        _gbComment.UseWaitCursor = true;
        // 
        // _txtKommentar
        // 
        _txtKommentar.Dock = DockStyle.Fill;
        _txtKommentar.Font = new Font("Segoe UI", 11F);
        _txtKommentar.Location = new Point(12, 30);
        _txtKommentar.Multiline = true;
        _txtKommentar.Name = "_txtKommentar";
        _txtKommentar.ScrollBars = ScrollBars.Vertical;
        _txtKommentar.Size = new Size(435, 0);
        _txtKommentar.TabIndex = 0;
        _txtKommentar.UseWaitCursor = true;
        // 
        // _right
        // 
        _right.BackColor = Color.White;
        _right.ColumnCount = 1;
        _right.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 20F));
        _right.Controls.Add(_listOuter, 0, 0);
        _right.Dock = DockStyle.Fill;
        _right.Location = new Point(524, 19);
        _right.Name = "_right";
        _right.RowCount = 1;
        _right.RowStyles.Add(new RowStyle(SizeType.Absolute, 20F));
        _right.Size = new Size(1302, 822);
        _right.TabIndex = 1;
        // 
        // _listOuter
        // 
        _listOuter.Controls.Add(_listLayout);
        _listOuter.Dock = DockStyle.Fill;
        _listOuter.Location = new Point(3, 3);
        _listOuter.Name = "_listOuter";
        _listOuter.Padding = new Padding(12);
        _listOuter.Size = new Size(1296, 816);
        _listOuter.TabIndex = 0;
        _listOuter.TabStop = false;
        _listOuter.Text = "Aktiv liste (kamera)";
        // 
        // _listLayout
        // 
        _listLayout.ColumnCount = 1;
        _listLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 20F));
        _listLayout.Controls.Add(_filterBar, 0, 0);
        _listLayout.Controls.Add(_header, 0, 1);
        _listLayout.Controls.Add(_grid, 0, 2);
        _listLayout.Dock = DockStyle.Fill;
        _listLayout.Location = new Point(12, 28);
        _listLayout.Margin = new Padding(0);
        _listLayout.Name = "_listLayout";
        _listLayout.RowCount = 3;
        _listLayout.RowStyles.Add(new RowStyle());
        _listLayout.RowStyles.Add(new RowStyle());
        _listLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        _listLayout.Size = new Size(1272, 776);
        _listLayout.TabIndex = 0;
        // 
        // _filterBar
        // 
        _filterBar.AutoSize = true;
        _filterBar.AutoSizeMode = AutoSizeMode.GrowAndShrink;
        _filterBar.ColumnCount = 16;
        _filterBar.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 80F));
        _filterBar.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 80F));
        _filterBar.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 38F));
        _filterBar.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 143F));
        _filterBar.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 35F));
        _filterBar.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 143F));
        _filterBar.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 9F));
        _filterBar.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 127F));
        _filterBar.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 39F));
        _filterBar.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 127F));
        _filterBar.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 29F));
        _filterBar.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 185F));
        _filterBar.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 8F));
        _filterBar.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 118F));
        _filterBar.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 191F));
        _filterBar.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 52F));
        _filterBar.Controls.Add(_btnRefresh, 7, 0);
        _filterBar.Controls.Add(_btnConfirm, 9, 0);
        _filterBar.Controls.Add(_lblPeriodeLabel, 0, 0);
        _filterBar.Controls.Add(_cmbPeriode, 1, 0);
        _filterBar.Controls.Add(_lblFraLabel, 2, 0);
        _filterBar.Controls.Add(_dtpFra, 3, 0);
        _filterBar.Controls.Add(_lblTilLabel, 4, 0);
        _filterBar.Controls.Add(_dtpTil, 5, 0);
        _filterBar.Controls.Add(_pnlCamStatus, 11, 0);
        _filterBar.Controls.Add(_btnSettings, 13, 0);
        _filterBar.Dock = DockStyle.Fill;
        _filterBar.Location = new Point(0, 0);
        _filterBar.Margin = new Padding(0);
        _filterBar.Name = "_filterBar";
        _filterBar.RowCount = 1;
        _filterBar.RowStyles.Add(new RowStyle(SizeType.Absolute, 32F));
        _filterBar.Size = new Size(1272, 32);
        _filterBar.TabIndex = 0;
        // 
        // _btnRefresh
        // 
        _btnRefresh.Dock = DockStyle.Fill;
        _btnRefresh.Font = new Font("Segoe UI", 11F, FontStyle.Bold);
        _btnRefresh.Location = new Point(531, 3);
        _btnRefresh.Name = "_btnRefresh";
        _btnRefresh.Size = new Size(121, 26);
        _btnRefresh.TabIndex = 9;
        _btnRefresh.Text = "Oppdater";
        // 
        // _btnConfirm
        // 
        _btnConfirm.AutoSize = true;
        _btnConfirm.AutoSizeMode = AutoSizeMode.GrowAndShrink;
        _btnConfirm.Dock = DockStyle.Fill;
        _btnConfirm.Font = new Font("Segoe UI", 11F, FontStyle.Bold);
        _btnConfirm.Location = new Point(697, 3);
        _btnConfirm.Name = "_btnConfirm";
        _btnConfirm.Size = new Size(121, 26);
        _btnConfirm.TabIndex = 8;
        _btnConfirm.Text = "Jeg har vasket";
        // 
        // _lblPeriodeLabel
        // 
        _lblPeriodeLabel.Dock = DockStyle.Fill;
        _lblPeriodeLabel.Font = new Font("Segoe UI", 11F, FontStyle.Bold);
        _lblPeriodeLabel.Location = new Point(3, 0);
        _lblPeriodeLabel.Name = "_lblPeriodeLabel";
        _lblPeriodeLabel.Size = new Size(74, 32);
        _lblPeriodeLabel.TabIndex = 0;
        _lblPeriodeLabel.Text = "Periode";
        _lblPeriodeLabel.TextAlign = ContentAlignment.MiddleLeft;
        // 
        // _cmbPeriode
        // 
        _cmbPeriode.Dock = DockStyle.Fill;
        _cmbPeriode.Font = new Font("Segoe UI", 11F);
        _cmbPeriode.Location = new Point(83, 3);
        _cmbPeriode.Name = "_cmbPeriode";
        _cmbPeriode.Size = new Size(74, 28);
        _cmbPeriode.TabIndex = 1;
        // 
        // _lblFraLabel
        // 
        _lblFraLabel.Dock = DockStyle.Fill;
        _lblFraLabel.Font = new Font("Segoe UI", 11F, FontStyle.Bold);
        _lblFraLabel.Location = new Point(163, 0);
        _lblFraLabel.Name = "_lblFraLabel";
        _lblFraLabel.Size = new Size(32, 32);
        _lblFraLabel.TabIndex = 2;
        _lblFraLabel.Text = "Fra";
        _lblFraLabel.TextAlign = ContentAlignment.MiddleLeft;
        // 
        // _dtpFra
        // 
        _dtpFra.Dock = DockStyle.Fill;
        _dtpFra.Font = new Font("Segoe UI", 11F);
        _dtpFra.Location = new Point(201, 3);
        _dtpFra.Name = "_dtpFra";
        _dtpFra.Size = new Size(137, 27);
        _dtpFra.TabIndex = 3;
        // 
        // _lblTilLabel
        // 
        _lblTilLabel.Dock = DockStyle.Fill;
        _lblTilLabel.Font = new Font("Segoe UI", 11F, FontStyle.Bold);
        _lblTilLabel.Location = new Point(344, 0);
        _lblTilLabel.Name = "_lblTilLabel";
        _lblTilLabel.Size = new Size(29, 32);
        _lblTilLabel.TabIndex = 4;
        _lblTilLabel.Text = "Til";
        _lblTilLabel.TextAlign = ContentAlignment.MiddleLeft;
        // 
        // _dtpTil
        // 
        _dtpTil.Dock = DockStyle.Fill;
        _dtpTil.Font = new Font("Segoe UI", 11F);
        _dtpTil.Location = new Point(379, 3);
        _dtpTil.Name = "_dtpTil";
        _dtpTil.Size = new Size(137, 27);
        _dtpTil.TabIndex = 5;
        // 
        // _pnlCamStatus
        // 
        _pnlCamStatus.BackColor = Color.Firebrick;
        _pnlCamStatus.BorderStyle = BorderStyle.FixedSingle;
        _pnlCamStatus.Controls.Add(_lblCamStatus);
        _pnlCamStatus.Location = new Point(850, 0);
        _pnlCamStatus.Margin = new Padding(0);
        _pnlCamStatus.Name = "_pnlCamStatus";
        _pnlCamStatus.Padding = new Padding(6, 0, 6, 0);
        _pnlCamStatus.Size = new Size(179, 30);
        _pnlCamStatus.TabIndex = 6;
        // 
        // _lblCamStatus
        // 
        _lblCamStatus.Dock = DockStyle.Fill;
        _lblCamStatus.Font = new Font("Segoe UI", 10F, FontStyle.Bold);
        _lblCamStatus.ForeColor = Color.White;
        _lblCamStatus.Location = new Point(6, 0);
        _lblCamStatus.Name = "_lblCamStatus";
        _lblCamStatus.Size = new Size(165, 28);
        _lblCamStatus.TabIndex = 0;
        _lblCamStatus.Text = "Kamera: Ikke aktiv";
        _lblCamStatus.TextAlign = ContentAlignment.MiddleCenter;
        // 
        // _btnSettings
        // 
        _btnSettings.AutoSize = true;
        _btnSettings.AutoSizeMode = AutoSizeMode.GrowAndShrink;
        _btnSettings.Dock = DockStyle.Fill;
        _btnSettings.Font = new Font("Segoe UI", 11F, FontStyle.Bold);
        _btnSettings.Location = new Point(1046, 3);
        _btnSettings.Name = "_btnSettings";
        _btnSettings.Size = new Size(112, 26);
        _btnSettings.TabIndex = 7;
        _btnSettings.Text = "Innstillinger";
        // 
        // _header
        // 
        _header.AutoSize = true;
        _header.AutoSizeMode = AutoSizeMode.GrowAndShrink;
        _header.ColumnCount = 14;
        _header.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 64F));
        _header.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 8F));
        _header.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 228F));
        _header.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 12F));
        _header.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 155F));
        _header.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 12F));
        _header.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 70F));
        _header.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 110F));
        _header.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 92F));
        _header.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 12F));
        _header.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 140F));
        _header.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 12F));
        _header.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        _header.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 1F));
        _header.Controls.Add(_lblAnsLabel, 0, 0);
        _header.Controls.Add(_cmbAnsatt, 2, 0);
        _header.Controls.Add(_chkOnlyUnconfirmed, 4, 0);
        _header.Controls.Add(_lblInternPickLabel, 6, 0);
        _header.Controls.Add(_cmbInternPick, 7, 0);
        _header.Controls.Add(_btnLagreSjekket, 8, 0);
        _header.Controls.Add(_lblDbStatus, 10, 0);
        _header.Controls.Add(_lblStatus, 12, 0);
        _header.Dock = DockStyle.Fill;
        _header.Location = new Point(0, 32);
        _header.Margin = new Padding(0);
        _header.Name = "_header";
        _header.RowCount = 1;
        _header.RowStyles.Add(new RowStyle(SizeType.Absolute, 35F));
        _header.Size = new Size(1272, 35);
        _header.TabIndex = 1;
        // 
        // _lblAnsLabel
        // 
        _lblAnsLabel.Dock = DockStyle.Fill;
        _lblAnsLabel.Font = new Font("Segoe UI", 11F, FontStyle.Bold);
        _lblAnsLabel.Location = new Point(3, 0);
        _lblAnsLabel.Name = "_lblAnsLabel";
        _lblAnsLabel.Size = new Size(58, 35);
        _lblAnsLabel.TabIndex = 0;
        _lblAnsLabel.Text = "Ansatt";
        _lblAnsLabel.TextAlign = ContentAlignment.MiddleLeft;
        // 
        // _cmbAnsatt
        // 
        _cmbAnsatt.Dock = DockStyle.Fill;
        _cmbAnsatt.Font = new Font("Segoe UI", 11F);
        _cmbAnsatt.Location = new Point(75, 3);
        _cmbAnsatt.Name = "_cmbAnsatt";
        _cmbAnsatt.Size = new Size(222, 28);
        _cmbAnsatt.TabIndex = 1;
        // 
        // _chkOnlyUnconfirmed
        // 
        _chkOnlyUnconfirmed.AutoSize = true;
        _chkOnlyUnconfirmed.Dock = DockStyle.Left;
        _chkOnlyUnconfirmed.Font = new Font("Segoe UI", 11F);
        _chkOnlyUnconfirmed.Location = new Point(315, 3);
        _chkOnlyUnconfirmed.Name = "_chkOnlyUnconfirmed";
        _chkOnlyUnconfirmed.Size = new Size(147, 29);
        _chkOnlyUnconfirmed.TabIndex = 2;
        _chkOnlyUnconfirmed.Text = "Kun ikke bekreftet";
        // 
        // _lblInternPickLabel
        // 
        _lblInternPickLabel.Dock = DockStyle.Fill;
        _lblInternPickLabel.Enabled = false;
        _lblInternPickLabel.Font = new Font("Segoe UI", 11F, FontStyle.Bold);
        _lblInternPickLabel.Location = new Point(482, 0);
        _lblInternPickLabel.Name = "_lblInternPickLabel";
        _lblInternPickLabel.Size = new Size(64, 35);
        _lblInternPickLabel.TabIndex = 20;
        _lblInternPickLabel.Text = "Internnr.";
        _lblInternPickLabel.TextAlign = ContentAlignment.MiddleCenter;
        // 
        // _cmbInternPick
        // 
        _cmbInternPick.Dock = DockStyle.Fill;
        _cmbInternPick.DropDownStyle = ComboBoxStyle.DropDownList;
        _cmbInternPick.Enabled = false;
        _cmbInternPick.Font = new Font("Segoe UI", 11F);
        _cmbInternPick.FormattingEnabled = true;
        _cmbInternPick.Location = new Point(552, 3);
        _cmbInternPick.Name = "_cmbInternPick";
        _cmbInternPick.Size = new Size(104, 28);
        _cmbInternPick.TabIndex = 21;
        // 
        // _btnLagreSjekket
        // 
        _btnLagreSjekket.Dock = DockStyle.Fill;
        _btnLagreSjekket.Enabled = false;
        _btnLagreSjekket.Font = new Font("Segoe UI", 11F, FontStyle.Bold);
        _btnLagreSjekket.Location = new Point(662, 3);
        _btnLagreSjekket.Name = "_btnLagreSjekket";
        _btnLagreSjekket.Size = new Size(86, 29);
        _btnLagreSjekket.TabIndex = 22;
        _btnLagreSjekket.Text = "Lagre";
        // 
        // _lblDbStatus
        // 
        _lblDbStatus.Dock = DockStyle.Fill;
        _lblDbStatus.Font = new Font("Segoe UI", 11F, FontStyle.Bold);
        _lblDbStatus.ForeColor = Color.Gray;
        _lblDbStatus.Location = new Point(763, 0);
        _lblDbStatus.Margin = new Padding(0, 0, 12, 0);
        _lblDbStatus.Name = "_lblDbStatus";
        _lblDbStatus.Size = new Size(128, 35);
        _lblDbStatus.TabIndex = 4;
        _lblDbStatus.Text = "DB: ...";
        _lblDbStatus.TextAlign = ContentAlignment.MiddleRight;
        // 
        // _lblStatus
        // 
        _lblStatus.Dock = DockStyle.Fill;
        _lblStatus.Font = new Font("Segoe UI", 11F);
        _lblStatus.Location = new Point(918, 0);
        _lblStatus.Name = "_lblStatus";
        _lblStatus.Size = new Size(350, 35);
        _lblStatus.TabIndex = 5;
        _lblStatus.Text = "Klar.";
        _lblStatus.TextAlign = ContentAlignment.MiddleLeft;
        // 
        // _grid
        // 
        _grid.Dock = DockStyle.Fill;
        _grid.Location = new Point(0, 67);
        _grid.Margin = new Padding(0);
        _grid.Name = "_grid";
        _grid.Size = new Size(1272, 709);
        _grid.TabIndex = 2;
        // 
        // WorkerForm
        // 
        AutoScaleDimensions = new SizeF(96F, 96F);
        AutoScaleMode = AutoScaleMode.Dpi;
        BackColor = Color.White;
        ClientSize = new Size(1845, 900);
        Controls.Add(_root);
        MinimumSize = new Size(1200, 700);
        Name = "WorkerForm";
        StartPosition = FormStartPosition.CenterScreen;
        Text = "Bilvask – Arbeiderliste";
        _root.ResumeLayout(false);
        _leftOuter.ResumeLayout(false);
        _left.ResumeLayout(false);
        _plateHost.ResumeLayout(false);
        _leftBottom.ResumeLayout(false);
        _leftBottom.PerformLayout();
        _gbType.ResumeLayout(false);
        _typeLayout.ResumeLayout(false);
        _gbComment.ResumeLayout(false);
        _gbComment.PerformLayout();
        _right.ResumeLayout(false);
        _listOuter.ResumeLayout(false);
        _listLayout.ResumeLayout(false);
        _listLayout.PerformLayout();
        _filterBar.ResumeLayout(false);
        _filterBar.PerformLayout();
        _pnlCamStatus.ResumeLayout(false);
        _header.ResumeLayout(false);
        _header.PerformLayout();
        ((ISupportInitialize)_grid).EndInit();
        ResumeLayout(false);
    }

    private Panel _pnlCamStatus;
    private Label _lblStatus;
    private Button _btnConfirm;
    private Button _btnRefresh;
    private Label _lblCamStatus;
    private RadioButton radioButton2;
}
